spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:50434/smartcampus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=NWRANectDCwbmZcNrfsRyHTXnuEdqCkC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver